on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.pixelaxis.net
        username: u803680896.pixelaxis
        password: "Pixelaxis@123"
        server-dir: "villea/"
        # This line automatically creates missing folders
        # create-dirs: true

        # Don’t delete everything each deploy
        dangerous-clean-slate: false